# BM - SS 24

## Einführung in Numpy
### Prof. Dr. Marcus Vetter

Die folgenden Beispiele führen in die Python Numpy-Bibliothek ein

In [1]:
import numpy as np
import matplotlib.pyplot as plt

Legen wir zunächst eine python Liste an

In [2]:
list = [1, 2, 3]
print(list)

[1, 2, 3]


Der Datentyp ist:

In [3]:
print( type(list) )

<class 'list'>


Wir können nun aus der Liste ein Array erstellen.

In [4]:
a = np.array( list )  

print( a )
print( type(a) )
print( a.dtype )

[1 2 3]
<class 'numpy.ndarray'>
int32


Das Erzeugen eines Array geht natürlich auch direkt

In [5]:
b = np.array( [1, 2, 3] ) 

print( b )
print( type(b) )
print( a.dtype )

[1 2 3]
<class 'numpy.ndarray'>
int32


np.array erwartet eine Liste

In [6]:
c  = np.array(1, 2, 3) # Dies führt zu einem Fehler

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

Im Folgenden wollen wir mittels der Funktion arange eine Liste von 1 bis 8 erstel:
Das erster Element begint mit 1.
Achtung die obere Schranke der Liste ist exclusiv!

In [7]:
c  = np.arange( 1, 9 )

print( c )

[1 2 3 4 5 6 7 8]


Wir können die Liste von eins bis 5 exclusiv des letzten Elements auch mit der Schrittweite 0.5 erstellen

In [ ]:
c  = np.arange( 1, 5, 0.5 )

print( c )
print( c.dtype )

Der lesende und schreibende Zugriff auf einzelne Elemente erfolgt über den Operator arrayName[index]

In [ ]:
print( c[0] )
print( c[1] )
c[0] = 20
c[1] = 25
print( c[0], c[1] )

### Mehrdimensionale Arrays
betrachten wir zunächst die Dimension von 

In [ ]:
print( c.shape )

Die Diemnsion ist ( 8, nix ).
Erzeugen wir nun ein Array der Dimension ( 2, 3 )

In [ ]:
c = np.array([[1,2,3],[4,5,6]])  
print(c)
print(c.shape)
print(c[0,0], c[0,1], c[0,2], c[1,0], c[1,1], c[1,2])

Wir können das Array der Dimension (2,3) auch aus Listen erstellen. Die Methode vstack erwartet dabei ein Tupel von Listen.

In [ ]:
c1 = [1,2,3]
c2 = [4,5,6]
c = np.vstack((c1,c2))
print(c)
print(c.shape)

Das Tupel darf dabei beliebig viele Elemente enthalten. 

In [ ]:
c3 = [7,8,9]
c = np.vstack((c1,c2,c3))
print(c)
print(c.shape)

Die Methode hsteck hängt die Listen hintereinander. Die Diemension ist dann aber wieder (9, nix)

In [ ]:
c = np.hstack((c1,c2,c3))
print(c)
print(c.shape)

Das gleiche geht auch anstelle mit Python-Listen mit numpy-Arrays

In [ ]:
b1 = np.array([1, 2])
b2 = np.array([3, 4])
b3 = np.array([5, 6])
b= np.hstack((b1,b2,b3))
print( b ) 
print( b.shape )

Wir könne auch Arrays der Dimension (2,1) horizontal Stacken

In [ ]:
b1 = np.array([[1], [4]])
print('b1 hat die Diemensio: ', b1.shape)
b2 = np.array([[2], [5]])
b3 = np.array([[3], [6]])
b= np.hstack((b1,b2,b3))
print( b ) 
print( b.shape )

Mittels der Methode reshape lassen sich numpy-Arrays auch umorganisieren

In [ ]:
b1 = np.array([1, 4]).reshape(2,1)
print( b1.shape )
b2 = np.array([2, 5]).reshape(2,-1) # eine dimension darf unbounded sein (-1)
print( b2.shape )
b3 = np.array([3, 6]).T             # einfach Transponieren geht nicht
print( b3.shape )
b3 = np.array([3, 6]).reshape(1,2).T #
print( b3.shape )

In [ ]:
b= np.hstack((b1,b2,b3))
print( b )
print( b.shape )

Wir können nun zunächst ein Array der Dimension (6,nix) erzeugen und dieses mittels reshape in die Dimension (2,3) umorganisieren

In [8]:
b = np.arange(1,7)
print( b )
print( b.shape )
b = np.arange(1,7).reshape(2,3) 
print(b)
print( b.shape )

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


Mittels der Methode flatten können wir ein Zweidimensionales Array wieder um eine Dimension verringern

In [ ]:
b = b.flatten()
print( b )
print( b.shape )

### Spezielle Konstruktoren

In [ ]:
c = np.zeros((4,2))
print( c )

In [ ]:
c = np.ones_like(b)
print( c )

In [ ]:
c = np.diag(np.array([1, 2, 3, 4, 5]))
print( c )

In [ ]:
c = np.eye(4)
print( c )

In [ ]:
c = np.kron( np.diag([1,2,3]), np.ones((2,3)) )
print( c )

In [ ]:
c = np.linspace(1, 2, 5)
print( c )
print(c.shape)

In [ ]:
x = np.linspace(0, 1, 5)
print('x:', x)
y = np.arange(0, 1, 0.25)
print('y:', y)
xx, yy = np.meshgrid(x, y)
print('xx:', xx)
print('yy:', yy)

### Datentypen

In [ ]:
b = np.array([1, 2, 3])  
print( type(b) )
print( b.dtype )

In [ ]:
b = np.array([1., 2., 3.])  
print( type(b))
print( b.dtype )

In [ ]:
b = np.array([1, 2, 3], dtype=np.float64)  
print( type(b))
print( b.dtype )

In [ ]:
b = np.diag(np.arange(1,6))
print( b.dtype )

In [ ]:
b = np.ones_like(b)
print( b.dtype )

In [ ]:
b = np.zeros(3) # Sonderfall !
print( b.dtype )

In [ ]:
print( 3./2. )
print( 3/2 ) # neu mit python 3.x

## Matrix Operationen

In [ ]:
A = np.array([[1. ,2. ],[3. ,4. ]])
B = np.array([[5. ,6. ],[7. ,8. ]])
C = np.ones_like(A)

C = A + B

print( C )

In [ ]:
print( A )
print('----------')
print( B )
print('----------')
print( A + B )
print('----------')
print( np.add(A,B))

In [ ]:
print(A-B)
print('----------')
print( A*B )
print('----------')
print( A/B )
print('----------')
print( np.sqrt(A) )

In [ ]:
x = np.array([1, 2])
y = np.array([3, 4])
print( x.dot(y) )
print( np.dot(x, y))

In [ ]:
print( x.shape )
y = y.reshape(1,2)
x = x.reshape(2,1)
print( x.dot(y) )
print('----------')
print( y.dot(x) )
print( y.shape )

### Matrix Vector

In [ ]:
A = np.array([[1. ,2. ],[3. ,4. ]])
print( A )
print( A.shape )
print('----------')
x = np.array([1, 2])
print( x )
print( x.shape )
print('----------')
print( A+x ) # Dieses Verhalten wird als Broadcasting bezeichnet. 

In [ ]:
x = x.reshape(2,1)
print( A+x )

In [ ]:
print(A)
print(x)
print("----")
x = x.reshape(1,2)
print( A+x.reshape(1,2) )

In [ ]:
print( A*2 )

In [ ]:
print( A )
print('----------')
print( A.T )

### In arrays addressieren

In [9]:
v = np.arange(10)
print( v )

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print( v[2] )

In [ ]:
print( v[3:7] )

In [ ]:
print( v[:] )

In [ ]:
print( v[-1] ) # letztes Element

In [ ]:
print( v[3:10:3] ) # Schrittweite 3

In [ ]:
print( v[3::3] ) # bis zum Ende

In [ ]:
print( v[::] )

In [ ]:
print( v[:4] ) # Bis zum 4. Element

In [ ]:
print( v[4:] ) # Ab dem 4. Element

In [ ]:
v[-1] = 10 # Ersetzen des letzten Elements
print( v )

In [ ]:
b = np.arange(25).reshape(5,-1)  
print (b)
print( b.shape )

In [ ]:
print( b[1,2] )

In [ ]:
print( b[0] )

In [ ]:
a = b[:,0]
print( a )
print( a.shape )

In [ ]:
a = b[:1]
print( a )
print( a.shape )
print( a[0] )

In [ ]:
print(b)
print('----------')
print(b[3:, :3])

In [ ]:
print( b[:,::3] )

In [10]:
print( b )
print( b[:,[2, 3, 4, 1, 0]] )

[[1 2 3]
 [4 5 6]]


IndexError: index 3 is out of bounds for axis 1 with size 3

In [ ]:
boolIdx  = b < 10 # ergibt bool
print( boolIdx )

In [ ]:
print( b )
print( b[boolIdx])

In [ ]:
print( b[b > 10] )

In [ ]:
print( b.flat[10] )

In [ ]:
print( b.flat[5:10] )
print( b.flat[5:10].shape )

In [ ]:
b[0,:] = np.arange(4,-1,-1)
print( b )

### Views (Shallow/Deep Copy)

In [ ]:
A = np.zeros((5,5))
print( A )

In [ ]:
B = A[1:4,1:4] # flache kopie
print( B )
type( B )

In [ ]:
A[2, 2] = A[2, 2] +1
print( A )
print( B )

In [ ]:
B[1]=1
print( A )
print( B )

In [ ]:
B += 1
print( B )
print( A )

In [ ]:
B = B + 1
print( B )
print( A )

In [ ]:
C = B
C += B
B[1,1] = 1
print( C )

## Random Data generieren

In [ ]:
np.random.seed(3)
A = np.random.randn(2,2)
print( A )

In [ ]:
x = np.random.rand(50)
y = np.random.rand(50)
print(x)
print(y)

In [ ]:
plt.scatter(x, y)
plt.show()

In [ ]:
plt.plot((0, 1),(0,1), '--r')

In [ ]:
plt.scatter(x, y)
plt.plot((0, 1),(0,1), '--r')
plt.show()